spring:
  profiles: default
  application:
    name: car-wash-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: car-wash
logging:
  level:
    root: INFO
server:
  port: 9092


user.profile.service.criteria.uri: http://localhost:9090/user-profile-service/criteria
car.details.service.criteria.uri: http://localhost:9091/car-details-service/criteria
user.profile.service.user-wash-count-update.uri: http://localhost:9090/user-profile-service/updateUserWashCount

mail.smtp.host: smtp.gmail.com
mail.smtp.socketFactory.port: 465
mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
mail.smtp.auth: true
mail.smtp.port: 465

data.transform.queue: user.review.queue
user.profile.update.queue: user.wash.count.update.queue
