spring:
  profiles: default
  application:
    name: car-wash-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: car-wash
logging:
  level:
    root: INFO
server:
  port: 8081


user.profile.service.criteria.uri: http://localhost:9090/user-profile-service/criteria
